#!/usr/bin/env python3
"""Offline, deterministic Markdown catalog and quality checks, Python 3.10+.

Markdown is the only source. Never executes article code, visits links, infers
primary CVEs from body text, rewrites articles, or deletes duplicate candidates.
"""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
import hashlib
from html.parser import HTMLParser
import json
import os
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys
from urllib.parse import quote, unquote, urlsplit

ROOTS = ("Web安全", "系统安全", "IOT安全")
GENERATED = "docs/generated"
VERSION = 1
ENUMS = {
    "record_type": {"vulnerability", "analysis", "advisory", "incident", "roundup", "unknown"},
    "review_status": {"text-reviewed", "unreviewed"},
    "verification_status": {"not-reproduced", "source-claimed", "reproduced", "failed", "unknown"},
    "content_status": {"active", "needs-review", "quarantined", "rejected"},
    "identifier_status": {"active", "rejected", "disputed", "unknown"},
    "identifier_role": {"primary", "reference", "unknown"},
    "source_status": {"recorded", "unknown", "missing"},
    "relation_type": {"duplicate_of", "analysis_of", "chained_with", "patch_bypass_of", "supersedes"},
}
IDENTIFIERS = {
    "CVE": re.compile(r"CVE-\d{4}-\d{4,}"),
    "CNVD": re.compile(r"CNVD-(?:C-)?\d{4}-\d{4,}"),
    "CNNVD": re.compile(r"CNNVD-\d{6}-\d{3,}"),
    "GHSA": re.compile(r"GHSA-[23456789cfghjmpqrvwx]{4}-[23456789cfghjmpqrvwx]{4}-[23456789cfghjmpqrvwx]{4}"),
    "QVD": re.compile(r"QVD-\d{4}-\d{4,}"),
    "XVE": re.compile(r"XVE-\d{4}-\d{4,}"),
}
DOM_EVENTS = set("abort afterprint animationcancel animationend animationiteration animationstart auxclick beforeinput beforematch beforeprint beforetoggle beforeunload blur cancel canplay canplaythrough change click close contextlost contextmenu contextrestored copy cuechange cut dblclick drag dragend dragenter dragleave dragover dragstart drop durationchange emptied ended error focus focusin focusout formdata fullscreenchange fullscreenerror gotpointercapture hashchange input invalid keydown keypress keyup languagechange load loadeddata loadedmetadata loadstart lostpointercapture message messageerror mousedown mouseenter mouseleave mousemove mouseout mouseover mouseup offline online pagehide pageshow paste pause play playing pointercancel pointerdown pointerenter pointerleave pointermove pointerout pointerover pointerrawupdate pointerup popstate progress ratechange rejectionhandled reset resize scroll scrollend securitypolicyviolation seeked seeking select selectionchange selectstart slotchange stalled storage submit suspend timeupdate toggle touchcancel touchend touchmove touchstart transitioncancel transitionend transitionrun transitionstart unhandledrejection unload volumechange waiting webkitanimationend webkittransitionend wheel".split())
FATAL_CODES = {"encoding", "frontmatter", "field_type", "field_duplicate", "enum", "id_invalid", "id_duplicate", "path", "schema_required", "canonical", "relation", "verification_evidence", "active_html_example", "index_category"}
HEADER = "<!-- Generated by scripts/wiki.py; edit source Markdown, then rebuild. -->\n\n"


def digest(value):
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def json_text(value, pretty=False):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2 if pretty else None,
                      separators=None if pretty else (",", ":")) + "\n"


@dataclass(frozen=True, order=True)
class Issue:
    path: str
    code: str
    detail: str
    severity: str = "warning"
    line: int = 0

    @property
    def key(self):
        # Metadata insertions shift lines; retain occurrence counts separately.
        return digest(json_text([self.path, self.code, self.detail, self.severity]))[:24]


@dataclass
class Record:
    path: str
    metadata: dict
    body: str
    sha256: str
    issues: list = field(default_factory=list)
    primary: list = field(default_factory=list)
    candidates: list = field(default_factory=list)
    references: list = field(default_factory=list)
    fingerprints: dict = field(default_factory=dict)
    source_links: list = field(default_factory=list)

    def issue(self, code, detail, severity="warning", line=0):
        self.issues.append(Issue(self.path, code, detail, severity, line))

    @property
    def eligible(self):
        return self.metadata.get("content_status") not in {"quarantined", "rejected"} and not any(i.code in FATAL_CODES for i in self.issues)

    @property
    def product(self):
        return self.metadata.get("product") or "未确认产品"

    @property
    def title(self):
        return self.metadata.get("title") or PurePosixPath(self.path).stem

    @property
    def article_id(self):
        return self.metadata.get("id") or "legacy-path-" + digest(self.path)[:24]

    @property
    def index_category(self):
        if self.metadata.get("index_category"):
            return self.metadata["index_category"]
        parts = PurePosixPath(self.path).parts
        return "/".join(parts[:2]) if len(parts) > 2 else parts[0]


def parse_frontmatter(text):
    """Small scalar-only reader; unknown strings and legacy draft/tags survive.

    Returns metadata, original untouched body and (code, detail, line) errors.
    New values use JSON double-quoted or YAML single-quoted scalar strings.
    """
    if not text.startswith(("---\n", "---\r\n")):
        return {}, text, []
    lines = text.splitlines(keepends=True)
    end = next((i for i, s in enumerate(lines[1:], 1) if s.strip() == "---"), None)
    if end is None:
        return {}, text, [("frontmatter", "unclosed frontmatter", 1)]
    meta, errors = {}, []
    for n, line in enumerate(lines[1:end], 2):
        if not line.strip() or line.strip().startswith("#"):
            continue
        match = re.fullmatch(r"([A-Za-z_][A-Za-z0-9_-]*):[ \t]*(.*?)[\r\n]*", line)
        if not match:
            errors.append(("frontmatter", "only single-line key: string fields are supported", n))
            continue
        key, raw = match.groups()
        if key in meta:
            errors.append(("field_duplicate", key, n))
            continue
        value = raw.strip()
        if key in {"draft", "tags"}:
            meta[key] = value  # Opaque historical Hexo fields, never vuln facts.
            continue
        code = "fingerprint_invalid" if key in {"fofa", "hunter", "quake"} else "field_type"
        if value.startswith('"'):
            try:
                value = json.loads(value)
            except (ValueError, TypeError):
                errors.append((code, key + ": use a JSON-quoted single-line string", n))
                continue
        elif value.startswith("'"):
            if not re.fullmatch(r"'(?:[^']|'')*'", value):
                errors.append((code, key + ": invalid single-quoted string; escape quotes as two single quotes", n))
                continue
            value = value[1:-1].replace("''", "'")
        elif (value and value[:1] in "[{|>") or re.fullmatch(r"(?i:true|false|null|~|[-+]?\d+(?:\.\d+)?)", value):
            errors.append((code, key + ": quote scalar values; collections are unsupported", n))
            continue
        elif value and (value[0] in "&*!%@`" or re.match(r"[-?:](?:\s|$)", value)
                        or re.search(r":(?:\s|$)|(?:^|\s)#", value)):
            errors.append((code, key + ": quote YAML syntax in scalar values", n))
            continue
        if not isinstance(value, str) or "\n" in value or "\r" in value:
            errors.append((code, key + ": expected a single-line string", n))
            continue
        meta[key] = value
    return meta, "".join(lines[end + 1:]), errors


def split_ids(value):
    return [x for x in re.split(r"[;,，；\s]+", value.strip()) if x]


def normalize_identifier(identifier):
    prefix = identifier.split("-", 1)[0].upper()
    if prefix == "GHSA" and "-" in identifier:
        return "GHSA-" + identifier.split("-", 1)[1].lower()
    return identifier.upper() if prefix in IDENTIFIERS else identifier


def valid_id(identifier):
    return any(p.fullmatch(identifier) for p in IDENTIFIERS.values())


def identifier_kind(identifier):
    if valid_id(identifier):
        return "known"
    if identifier.split("-", 1)[0].upper() not in IDENTIFIERS and re.fullmatch(r"[A-Za-z][A-Za-z0-9]*(?:-[A-Za-z0-9]+)+", identifier):
        return "unrecognized"
    return "invalid"


def fingerprint_valid(query):
    """Conservative syntax-only subset, NOT platform or vulnerability validation."""
    token = re.compile(r'\s*(\&\&|\|\||!=|==|>=|<=|[()!<>=]|[A-Za-z_][\w.:-]*|"(?:\\.|[^"\\])*"|\d+)')
    tokens, pos = [], 0
    while pos < len(query):
        if query[pos:].isspace():
            break
        match = token.match(query, pos)
        if not match:
            return False
        tokens.append(match[1])
        pos = match.end()
    index = 0

    def atom():
        nonlocal index
        if index < len(tokens) and tokens[index] == "!":
            index += 1
            return atom()
        if index < len(tokens) and tokens[index] == "(":
            index += 1
            ok = expression()
            if index >= len(tokens) or tokens[index] != ")":
                return False
            index += 1
            return ok
        if index + 2 >= len(tokens):
            return False
        key, op, val = tokens[index:index + 3]
        if not re.fullmatch(r"[A-Za-z_][\w.:-]*", key) or op not in {"=", "==", "!=", ">", "<", ">=", "<="}:
            return False
        if not (re.fullmatch(r'"(?:\\.|[^"\\])+"', val) or val.isdigit()):
            return False
        index += 3
        return True

    def expression():
        nonlocal index
        if not atom():
            return False
        while index < len(tokens) and tokens[index] in {"&&", "||"}:
            index += 1
            if not atom():
                return False
        return True
    try:
        return bool(tokens) and expression() and index == len(tokens)
    except RecursionError:
        return False


def prose_and_fences(body):
    """Blank fenced/indented code only for analysis; preserve source and lines."""
    output, issues, opened, content = [], [], None, []
    for n, line in enumerate(body.splitlines(keepends=True), 1):
        match = re.match(r"^ {0,3}(`{3,}|~{3,})(.*)$", line.rstrip("\r\n"))
        if opened:
            if match and match[1][0] == opened[0] and len(match[1]) >= opened[1] and not match[2].strip():
                if not "".join(content).strip():
                    issues.append(("empty_fence", "empty code fence", opened[2]))
                opened, content = None, []
            else:
                content.append(line)
            output.append("\n")
        elif match:
            opened = (match[1][0], len(match[1]), n)
            output.append("\n")
        else:
            output.append(line)
    if opened:
        issues.append(("unclosed_fence", "unclosed code fence", opened[2]))
    visible, indented, previous_blank = [], False, True
    for line in output:
        if not line.strip():
            visible.append(line)
            previous_blank = True
            continue
        if line.startswith(("    ", "\t")) and (previous_blank or indented):
            visible.append("\n")
            indented = True
        else:
            visible.append(line)
            indented = False
        previous_blank = False
    return "".join(visible), issues


class HtmlLinks(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links, self.active = [], []

    def handle_starttag(self, tag, attrs):
        # Raw <pre>/<code> preserve whitespace, not HTML: nested tags still
        # execute. Actual Markdown code has already been removed by the caller.
        if tag in {"script", "iframe", "object", "embed", "base"}:
            self.active.append(("active tag <" + tag + ">", self.getpos()[0]))
        for key, value in attrs:
            if key.startswith("on") and key[2:] in DOM_EVENTS:
                self.active.append(("event attribute " + tag + "." + key, self.getpos()[0]))
            if value and key in {"href", "src", "action", "formaction", "xlink:href"} and active_url(value):
                self.active.append(("active URL in " + tag + "." + key, self.getpos()[0]))
            if value and ((tag == "img" and key == "src") or (tag == "a" and key == "href")):
                self.links.append((value, tag == "img", self.getpos()[0]))


def active_url(value):
    return bool(re.match(r"(?i)^(?:(?:javascript|vbscript):|data:text/html(?:[;,]|$))",
                         re.sub(r"[\x00-\x20]", "", value)))


def markdown_links(prose, with_lines=False):
    """Inline/reference links, balanced parentheses, HTML and line positions."""
    prose = re.sub(r"(`+).*?\1", "", prose)
    refs = {m[1].casefold(): m[2].strip("<>") for m in re.finditer(r"(?m)^ {0,3}\[([^]\n]+)\]:\s*(<[^>]+>|\S+)", prose)}
    links = []
    cursor = 0
    opening = re.compile(r"(!?)\[")
    while match := opening.search(prose, cursor):
        cursor = match.end()
        backslashes, previous = 0, cursor - 2
        while previous >= 0 and prose[previous] == "\\":
            backslashes += 1
            previous -= 1
        if backslashes % 2:
            continue
        # Importers sometimes leave nested brackets in image descriptions.
        # Follow the outer label so the real destination is checked once.
        depth, end, escaped = 1, cursor, False
        while end < len(prose):
            c = prose[end]
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == "[":
                depth += 1
            elif c == "]":
                depth -= 1
                if not depth:
                    break
            elif c == "\n" and re.match(r"[ \t]*\r?\n", prose[end + 1:]):
                break
            end += 1
        if depth or end + 1 >= len(prose) or prose[end + 1] not in "([":
            continue
        label = prose[match.end():end]
        image = bool(match[1])
        if image:
            backslashes, previous = 0, match.start() - 1
            while previous >= 0 and prose[previous] == "\\":
                backslashes += 1
                previous -= 1
            image = not backslashes % 2
        line = prose.count("\n", 0, match.start()) + 1
        # A link may wrap an image; that inner image still needs an asset check.
        if not image and "![" in label:
            links.extend((t, i, line + n - 1) for t, i, n in markdown_links(label, True) if i)
        start = end + 2
        if prose[end + 1] == "[":
            close = prose.find("]", start)
            if close == -1 or "\n" in prose[start:close]:
                continue
            key = (prose[start:close] or label).casefold()
            if key in refs:
                links.append((refs[key], image, line))
            cursor = close + 1
            continue
        if start < len(prose) and prose[start] == "<":
            end = prose.find(">", start + 1)
            if end != -1:
                links.append((prose[start + 1:end], image, line))
                cursor = end + 1
            continue
        depth, end, escaped = 1, start, False
        while end < len(prose):
            c = prose[end]
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if not depth:
                    break
            elif c == "\n":
                break
            end += 1
        if depth == 0:
            destination = re.sub(r'\s+["\'][^"\']*["\']\s*$', "", prose[start:end]).strip()
            links.append((re.sub(r"\\([() ])", r"\1", destination), image, line))
            cursor = end + 1
    html = HtmlLinks()
    try:
        html.feed(prose)
        links.extend(html.links)
    except (ValueError, AssertionError):
        pass
    return links if with_lines else [(t, i) for t, i, _ in links]


def source_candidates(metadata, body):
    found = {}
    pattern = re.compile(r"https?://[^\s<>\"'\]\[，。]+")

    def collect(text, basis):
        for match in pattern.finditer(text):
            url = match[0].rstrip(").;，。")
            try:
                parsed = urlsplit(url)
                if parsed.netloc and url not in found:
                    found[url] = {"url": url, "basis": basis, "verification_status": "unverified-link"}
            except ValueError:
                continue
    for key in ("source_url", "ref", "verification_source"):
        if metadata.get(key):
            collect(metadata[key], "metadata:" + key)
    prose, _ = prose_and_fences(body)
    section = False
    for line in prose.splitlines():
        label = bool(re.search(r"原文(?:链接|地址)?|参考(?:链接|资料|来源|文献)?|来源|[Rr]eferences?", line))
        if re.match(r"^\s*#{1,6}\s", line):
            section = label
        if label or section:
            collect(re.sub(r"!\[[^]]*\]\([^)]*\)", "", line), "body:labelled-reference")
    return list(found.values())


def repository_paths(root):
    """Only sparse skip-worktree files may fall back to Git HEAD."""
    try:
        tree = subprocess.check_output(["git", "ls-tree", "-rz", "--name-only", "HEAD"], cwd=root, stderr=subprocess.DEVNULL).decode().split("\0")
        entries = subprocess.check_output(["git", "ls-files", "-v", "-z"], cwd=root, stderr=subprocess.DEVNULL).decode().split("\0")
        return set(tree) & {x[2:] for x in entries if x[:1].upper() == "S"}
    except (OSError, subprocess.CalledProcessError, UnicodeError):
        return set()


def local_target(path, target):
    target = target.strip()
    if not target or target.startswith(("#", "//")):
        return None
    parsed = urlsplit(target)
    if parsed.scheme or parsed.netloc:
        return None
    # Split before decoding: %23 and %3F can be literal filename characters.
    target = unquote(parsed.path).replace("\\", "/")
    if not target:
        return None
    if target.startswith("/"):
        return "!site"
    normalized = os.path.normpath(str(PurePosixPath(path).parent / target)).replace(os.sep, "/")
    if normalized == ".." or normalized.startswith("../"):
        return "!outside"
    return normalized


def scan(root):
    records, sparse = [], repository_paths(root)
    for content_root in ROOTS:
        for file in sorted((root / content_root).rglob("*.md")):
            if ".resource" in file.parts:
                continue
            path = file.relative_to(root).as_posix()
            raw = b"" if file.is_symlink() else file.read_bytes()
            encoding_error = False
            try:
                text = raw.decode("utf-8")
            except UnicodeError:
                text = raw.decode("utf-8", errors="replace")
                encoding_error = True
            meta, body, errors = parse_frontmatter(text)
            r = Record(path, meta, body, hashlib.sha256(raw).hexdigest())
            records.append(r)
            if encoding_error:
                r.issue("encoding", "file is not valid UTF-8", "error")
            for code, detail, line in errors:
                r.issue(code, detail, "error", line)
            if file.is_symlink() or "\n" in path:
                r.issue("path", "symlink or newline in path", "error")
            if path.endswith(".md.md"):
                r.issue("path_legacy", "duplicate .md extension retained for existing links")
            for key, choices in ENUMS.items():
                if key in meta and meta[key] not in choices:
                    r.issue("enum", key + ": unsupported value", "error")
            if "index_category" in meta:
                category = meta["index_category"]
                parts = category.split("/")
                if (len(parts) != 2 or parts[0] not in ROOTS or not parts[1].strip()
                        or parts[1] != parts[1].strip()
                        or parts[1] in {".", ".."} or any(c in category for c in "\\\r\n")):
                    r.issue("index_category", "expected content root/category: " + category, "error")
            for key in ("id", "entity_id"):
                if meta.get(key) and not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}", meta[key]):
                    r.issue("id_invalid", key, "error")
            if not meta.get("id"):
                r.issue("legacy_id", "missing stable article id; provisional path hash used")
            if not meta.get("product"):
                r.issue("product_unknown", "product is not explicitly identified")
            if not meta.get("record_type"):
                r.issue("type_unknown", "record_type is unknown")
            if meta.get("schema_version") == "1":
                for key in ("id", "title", "product", "record_type", "review_status", "verification_status", "content_status", "prerequisites", "side_effects"):
                    if not meta.get(key):
                        r.issue("schema_required", key, "error")
                if not meta.get("source_url") and meta.get("source_status") not in {"unknown", "missing"}:
                    r.issue("schema_required", "source_url or explicit source_status=unknown/missing", "error")
            elif meta.get("schema_version"):
                r.issue("schema_required", "unsupported schema_version", "error")
            if meta.get("verification_status") == "reproduced":
                for key in ("verification_environment", "verification_evidence", "verification_date"):
                    if not meta.get(key):
                        r.issue("verification_evidence", key + " is required for reproduced", "error")
            if meta.get("source_url"):
                try:
                    parsed = urlsplit(meta["source_url"])
                    bad = parsed.scheme not in {"http", "https"} or not parsed.netloc
                except ValueError:
                    bad = True
                if bad:
                    r.issue("source_url", "expected an http(s) URL with a host", "error")
            r.source_links = source_candidates(meta, body)
            if not meta.get("source_url") and meta.get("source_status") in {"unknown", "missing"}:
                r.issue("source_missing", "original source URL explicitly " + meta["source_status"] + "; reference links are not confirmed provenance")
            elif not r.source_links:
                r.issue("source_label_only" if meta.get("source") else "source_missing", "no traceable URL in source fields or labelled reference sections")
            ids = meta.get("primary_identifiers", "")
            for raw_value in split_ids(ids):
                value = normalize_identifier(raw_value)
                kind = identifier_kind(value)
                if kind in {"known", "unrecognized"}:
                    r.primary.append(value)
                    if kind == "unrecognized":
                        r.issue("unrecognized_identifier_namespace", "primary role retained; namespace format not validated: " + value)
                else:
                    r.issue("identifier_format", "primary identifier invalid: " + value, "error")
            for key, bucket, role in (("referenced_identifiers", r.references, "reference"),
                                      ("identifier_candidates", r.candidates, "candidate")):
                for raw_value in split_ids(meta.get(key, "")):
                    value = normalize_identifier(raw_value)
                    kind = identifier_kind(value)
                    if kind in {"known", "unrecognized"}:
                        bucket.append(value)
                        if kind == "unrecognized":
                            r.issue("unrecognized_identifier_namespace", role + " role retained; namespace format not validated: " + value)
                    else:
                        r.issue("identifier_format", role + " identifier invalid: " + value, "error")
            legacy_role_unknown = False
            for key in ("cve", "cnvd", "cnnvd", "ghsa", "qvd", "xve"):
                for raw_value in split_ids(meta.get(key, "")):
                    value = normalize_identifier(raw_value)
                    if not IDENTIFIERS[key.upper()].fullmatch(value):
                        r.issue("identifier_format", key + " contains invalid or wrong-namespace identifier: " + value, "error")
                    elif value not in r.primary and value not in r.references and value not in r.candidates:
                        if not ids and meta.get("identifier_role") == "primary":
                            r.primary.append(value)
                        elif meta.get("identifier_role") == "reference":
                            r.references.append(value)
                        else:
                            r.candidates.append(value)
                            legacy_role_unknown = True
            if legacy_role_unknown:
                r.issue("identifier_role_unknown", "legacy identifier candidates excluded from primary CVE index")
            if meta.get("identifier_status") in {"rejected", "disputed"}:
                r.issue("identifier_inactive", "primary identifiers excluded: " + meta["identifier_status"])
            for platform in ("fofa", "hunter", "quake"):
                if meta.get(platform + "_unverified"):
                    r.issue("fingerprint_unverified", platform + ": retained unverified query excluded from fingerprint index")
                query = meta.get(platform, "")
                if query:
                    if fingerprint_valid(query):
                        r.fingerprints[platform] = {"query": query, "syntax_status": "basic-checked", "verification_status": "unverified"}
                    else:
                        r.issue("fingerprint_invalid", platform + ": outside supported syntax or incomplete expression", "error")
            if meta.get("version") and re.search(r"(?i)(?:curl\s|wget\s|\b(?:select|insert|delete)\s.+\b(?:from|into)\b|HTTP/[12]\.|(?:&&|\|\|))", meta["version"]):
                r.issue("version_command", "version contains a command/query candidate; excluded from machine version", "error")
            if not body.strip():
                r.issue("empty_body", "body is empty", "error")
            prose, fence_issues = prose_and_fences(body)
            body_offset = text[:len(text) - len(body)].count("\n")
            for code, detail, line in fence_issues:
                r.issue(code, detail, line=body_offset + line)
            html = HtmlLinks()
            try:
                html.feed(re.sub(r"(`+).*?\1", "", prose))
                for detail, line in html.active:
                    r.issue("active_html_example", detail + "; preserve payload as visible code after manual review", "error", body_offset + line)
            except (ValueError, AssertionError):
                pass
            for target, image, line in markdown_links(prose, with_lines=True):
                line += body_offset
                if active_url(target):
                    # HTML links are also returned here; avoid reporting the
                    # same source tag twice while still covering Markdown links.
                    if not any(i.code == "active_html_example" and i.line == line for i in r.issues):
                        r.issue("active_html_example", "active URL in Markdown link; preserve payload as visible code after manual review", "error", line)
                try:
                    local = local_target(path, target)
                except ValueError:
                    r.issue("link_invalid", "invalid destination: " + target, "error", line)
                    continue
                if local is None:
                    continue
                if local == "!site":
                    if not any(i.code == "site_relative_link" for i in r.issues):
                        r.issue("site_relative_link", "origin-relative website links require original-site review; example: " + target, line=line)
                elif local == "!outside":
                    r.issue("link_outside", "relative destination escapes repository: " + target, "error", line)
                elif not (root / local).exists() and local not in sparse:
                    if image and (not re.search(r"\.(?:png|jpe?g|gif|svg|webp|bmp|ico)(?:$|[?#])", target, re.I) or any(x in target for x in ('"', "'", "$", "<?"))):
                        r.issue("embedded_code_candidate", "possible HTML/PHP example, inspect manually: " + target, line=line)
                    elif not image and not re.search(r"\.(?:md|pdf|html?|txt|zip|py|sh)(?:$|[?#])", target, re.I):
                        r.issue("noncontent_link_candidate", "possible source code or original-site route: " + target, line=line)
                    else:
                        r.issue("image_missing" if image else "link_missing", local, "error", line)
    by_id, by_path = defaultdict(list), {r.path: r for r in records}
    for r in records:
        by_id[r.article_id].append(r)
        canonical = r.metadata.get("canonical")
        if canonical:
            if canonical not in by_path or canonical.startswith("/") or ".." in PurePosixPath(canonical).parts:
                r.issue("canonical", "canonical must name content Markdown from repository root", "error")
            if canonical != r.path and not r.metadata.get("relation_type"):
                r.issue("relation", "non-self canonical needs relation_type", "error")
        elif r.metadata.get("relation_type"):
            r.issue("relation", "relation_type needs canonical target", "error")
    for same_id in by_id.values():
        if len(same_id) > 1:
            for r in same_id:
                r.issue("id_duplicate", r.article_id, "error")
    for r in records:
        seen, current = set(), r
        while current.metadata.get("relation_type") == "duplicate_of" and current.metadata.get("canonical") in by_path and current.metadata.get("canonical") != current.path:
            if current.path in seen:
                r.issue("canonical", "canonical relationship cycle", "error")
                break
            seen.add(current.path)
            current = by_path[current.metadata["canonical"]]
    changed = True
    while changed:
        changed = False
        for r in records:
            target = r.metadata.get("canonical")
            if r.eligible and r.metadata.get("relation_type") == "duplicate_of" and target in by_path and not by_path[target].eligible:
                r.issue("canonical", "canonical target is quarantined or structurally invalid", "error")
                changed = True
    return records


def catalog_record(r):
    m = r.metadata
    result = {
        "id": r.article_id, "id_status": "stable" if m.get("id") else "provisional-path",
        "path": r.path, "sha256": r.sha256, "title": r.title, "product": r.product,
        "record_type": m.get("record_type", "unknown"),
        "content_status": m.get("content_status", "needs-review"),
        "review_status": m.get("review_status", "unreviewed"),
        "verification_status": m.get("verification_status", "not-reproduced"),
        "primary_identifiers": sorted(set(r.primary)) if m.get("identifier_status") not in {"rejected", "disputed"} else [],
        "identifier_status": m.get("identifier_status", "unknown"),
        "identifier_candidates": sorted(set(r.candidates)), "referenced_identifiers": sorted(set(r.references)),
        "source": {"status": m.get("source_status", "recorded" if m.get("source_url") else "unknown"), "label": m.get("source", ""), "url": m["source_url"] if m.get("source_url") and not any(i.code == "source_url" for i in r.issues) else "", "links": r.source_links},
        "fingerprints": r.fingerprints,
    }
    for key in ("entity_id", "canonical", "relation_type", "index_category", "category_recommendation", "prerequisites", "side_effects", "fixed_version", "verification_source", "archive_url", "archive_commit", "archive_title"):
        if m.get(key):
            result[key] = m[key]
    if m.get("version") and not any(i.code == "version_command" for i in r.issues):
        result["affected_version_claim"] = m["version"]
    return result


def duplicate_candidates(records):
    groups, exact, primary = [], defaultdict(list), defaultdict(list)
    for r in records:
        exact[digest(r.body)].append(r.path)
        for identifier in set(r.primary):
            primary[identifier].append(r.path)
    for basis, mapping in (("identical-body", exact), ("shared-primary-identifier", primary)):
        for value, paths in sorted(mapping.items()):
            if len(paths) > 1:
                groups.append({"basis": basis, "key": value, "paths": sorted(paths), "decision": "manual-review-required"})
    return groups


def escape_label(text):
    return text.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]").replace("\n", " ").replace("<", "&lt;").replace(">", "&gt;")


def md_link(label, target, origin):
    relative = os.path.relpath(target, str(PurePosixPath(origin).parent)).replace(os.sep, "/")
    return f"[{escape_label(label)}]({quote(relative, safe='/.-_~')})"


def render_outputs(records):
    sources = [r for r in records if r.eligible]
    by_path = {r.path: r for r in sources}

    def primary_path(record):
        seen = set()
        while record.metadata.get("relation_type") == "duplicate_of" and record.metadata.get("canonical") in by_path and record.metadata["canonical"] != record.path:
            if record.path in seen:
                break
            seen.add(record.path)
            record = by_path[record.metadata["canonical"]]
        return record.path
    source_groups = defaultdict(list)
    for r in sources:
        source_groups[primary_path(r)].append(r)
    usable = [r for r in sources if primary_path(r) == r.path]
    outputs, products, cves, entities = {}, defaultdict(list), defaultdict(list), defaultdict(list)
    for r in sources:
        if r.metadata.get("entity_id"):
            entities[r.metadata["entity_id"]].append(r)
    for r in usable:
        products[r.index_category.split("/")[-1]].append(r)
        if r.metadata.get("identifier_status") not in {"rejected", "disputed"}:
            for identifier in set(r.primary):
                if IDENTIFIERS["CVE"].fullmatch(identifier):
                    cves[identifier].append(r)
    index = [HEADER, "# 产品索引\n\n", f"收录 {len(usable)} 个主入口（另保留 {len(sources)} 份来源文档）；不代表独立漏洞数或已验证数量。隔离/无效记录和结构错误不进入本索引。\n\n"]
    for category, rows in sorted(products.items()):
        file = f"INDEX/{category}.md"
        index.append("- " + md_link(f"{category}（{len(rows)} 篇）", file, "INDEX.md") + "\n")
        text = [HEADER, f"# {escape_label(category)}\n\n", "产品按显式元数据分组；未确认产品不从目录自动推断。\n\n"]
        grouped = defaultdict(list)
        for r in rows:
            grouped[r.product].append(r)
        for product, articles in sorted(grouped.items()):
            text.append(f"## {escape_label(product)}\n\n")
            for r in sorted(articles, key=lambda x: (x.title, x.path)):
                text.append(f"- {md_link(r.title, r.path, file)} [{r.metadata.get('record_type', 'unknown')}; {r.metadata.get('verification_status', 'not-reproduced')}; {r.metadata.get('content_status', 'needs-review')}]\n")
                extra = [s for s in source_groups[r.path] if s.path != r.path]
                if extra:
                    text.append("  - 关联来源: " + " / ".join(md_link(s.title, s.path, file) for s in sorted(extra, key=lambda x: x.path)) + "\n")
            text.append("\n")
        outputs[file] = "".join(text)
    outputs["INDEX.md"] = "".join(index)
    years = defaultdict(list)
    for cve in cves:
        years[cve.split("-")[1]].append(cve)
    navigation = [HEADER, "# CVE 索引\n\n", "仅收录元数据明确声明的主编号。格式检查不等于官方核验；全文提及、旧字段未确认角色、撤销及争议编号不进入本索引。独立研究分别保留，仅明确 duplicate_of 折叠。\n\n"]
    for year, identifiers in sorted(years.items(), reverse=True):
        file = f"INDEX-CVE/year/{year}.md"
        navigation.append("- " + md_link(f"{year} 年（{len(identifiers)} 个主编号）", file, "INDEX-CVE.md") + "\n")
        text = [HEADER, f"# CVE {year}\n\n"]
        for cve in sorted(identifiers):
            text.append(f"## {cve}\n\n")
            for r in sorted(cves[cve], key=lambda x: x.path):
                text.append(f"- {md_link(r.title, r.path, file)} [编号状态: {r.metadata.get('identifier_status', 'unknown')}; {r.metadata.get('verification_status', 'not-reproduced')}]\n")
            text.append("\n")
        outputs[file] = "".join(text)
    outputs["INDEX-CVE.md"] = "".join(navigation)
    fingerprints = [HEADER, "# 指纹索引\n\n", "仅做保守子集的语法检查，未查询平台、未验证命中精度。资产发现不证明存在漏洞。无效/残缺表达式排除，原文仍保留。\n\n"]
    for platform in ("fofa", "hunter", "quake"):
        fingerprints.append(f"## {platform.upper()}\n\n")
        for r in sorted(usable, key=lambda x: x.path):
            if platform in r.fingerprints:
                query = r.fingerprints[platform]["query"].replace("`", "&#96;")
                fingerprints.append(f"- `{query}` — {md_link(r.title, r.path, 'INDEX-FOFA.md')}\n")
        fingerprints.append("\n")
    outputs["INDEX-FOFA.md"] = "".join(fingerprints)
    outputs[f"{GENERATED}/sources.jsonl"] = "".join(json_text(catalog_record(r)) for r in sorted(sources, key=lambda x: x.path))
    entry_keys = {"id", "path", "title", "product", "record_type", "content_status", "review_status", "verification_status", "primary_identifiers", "identifier_status", "identifier_candidates", "referenced_identifiers", "entity_id", "index_category"}
    outputs[f"{GENERATED}/records.jsonl"] = "".join(json_text({**{k: v for k, v in catalog_record(r).items() if k in entry_keys}, "source_record_ids": sorted(s.article_id for s in source_groups[r.path])}) for r in sorted(usable, key=lambda x: x.path))
    outputs[f"{GENERATED}/entities.jsonl"] = "".join(json_text({"entity_id": key, "source_record_ids": sorted(r.article_id for r in rows), "canonical_paths": sorted({r.metadata['canonical'] for r in rows if r.metadata.get('canonical')}), "grouping": "explicit-metadata"}) for key, rows in sorted(entities.items()))
    outputs[f"{GENERATED}/excluded.jsonl"] = "".join(json_text({"path": r.path, "content_status": r.metadata.get("content_status", "needs-review"), "blocking_checks": sorted({i.code for i in r.issues if i.code in FATAL_CODES})}) for r in records if not r.eligible)
    queue = [HEADER, "# 待核与隔离文档\n\n", "原始文档保留用于纠错追溯，不属于有效产品/CVE/指纹检索结果。\n\n"]
    for r in records:
        if not r.eligible:
            queue.append("- " + md_link(r.title, r.path, "docs/REVIEW-QUEUE.md") + " [" + r.metadata.get("content_status", "needs-review") + "]\n")
    outputs["docs/REVIEW-QUEUE.md"] = "".join(queue)
    outputs[f"{GENERATED}/duplicate-candidates.json"] = json_text(duplicate_candidates(records), True)
    outputs[f"{GENERATED}/summary.json"] = json_text({"schema_version": VERSION, "documents": len(records), "indexed_sources": len(sources), "primary_entries": len(usable), "excluded_sources": len(records) - len(sources), "explicit_entities": len(entities), "primary_cve_identifiers": len(cves), "fingerprints": sum(len(r.fingerprints) for r in usable), "issues": dict(sorted(Counter(i.code for r in records for i in r.issues).items())), "source_digest": digest("\n".join(r.path + ":" + r.sha256 for r in records)), "verification": "offline-static-only"}, True)
    return {p: text.rstrip() + "\n" if p.endswith(".md") else text for p, text in outputs.items()}


def output_paths(root):
    return {p.relative_to(root).as_posix() for folder in ("INDEX", "INDEX-CVE", GENERATED) for p in (root / folder).rglob("*") if p.is_file()} | {"INDEX.md", "INDEX-CVE.md", "INDEX-FOFA.md"}


def build(root, records, check=False):
    outputs = render_outputs(records)
    for old in sorted(output_paths(root)):
        if old not in outputs and old.endswith(".md") and old.startswith(("INDEX/", "INDEX-CVE/")):
            target = "INDEX-CVE.md" if old.startswith("INDEX-CVE/") else "INDEX.md"
            outputs[old] = HEADER + "# 索引已更新\n\n" + md_link("查看当前索引", target, old) + "\n"
    differences = []
    for name, text in sorted(outputs.items()):
        path = root / name
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            differences.append(name)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    return differences


def issue_summary(records):
    issues = sorted(i for r in records for i in r.issues)
    return issues, {"documents": len(records), "errors": sum(i.severity == "error" for i in issues), "warnings": sum(i.severity == "warning" for i in issues), "fatal_issues": sum(i.code in FATAL_CODES for i in issues), "by_code": dict(sorted(Counter(i.code for i in issues).items()))}


def write_baseline(path, issues, reason):
    if any(i.code in FATAL_CODES for i in issues):
        raise ValueError("fatal issues cannot be accepted into a quality baseline")
    groups = defaultdict(list)
    for issue in issues:
        groups[issue.key].append(issue)
    data = {"schema_version": VERSION, "reason": reason, "policy": "accepted historical debt, not a passing quality verdict; no new issues; fatal checks always block", "issues": [{**asdict(rows[0]), "key": key, "count": len(rows), "lines": sorted(i.line for i in rows)} for key, rows in sorted(groups.items())]}
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json_text(data, True), encoding="utf-8")


def baseline_delta(issues, baseline):
    old = Counter({x["key"]: x["count"] for x in baseline["issues"]})
    new = Counter(i.key for i in issues)
    return new - old, old - new


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    sub = parser.add_subparsers(dest="command", required=True)
    check = sub.add_parser("check", help="report all debt; baseline permits only existing nonfatal issues")
    check.add_argument("--baseline", type=Path)
    check.add_argument("--report", type=Path)
    baseline = sub.add_parser("baseline", help="explicit, reviewed historical nonfatal debt snapshot")
    baseline.add_argument("--output", type=Path, default=Path("docs/quality-baseline.json"))
    baseline.add_argument("--reason", required=True)
    generate = sub.add_parser("build", help="derive indexes; never edit source articles")
    generate.add_argument("--check", action="store_true")
    search = sub.add_parser("search", help="search generated metadata; never infer body identifiers")
    search.add_argument("query")
    search.add_argument("--type", choices=sorted(ENUMS["record_type"]))
    search.add_argument("--verification", choices=sorted(ENUMS["verification_status"]))
    search.add_argument("--entity")
    search.add_argument("--include-sources", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    if args.command == "search":
        file = root / GENERATED / ("sources.jsonl" if args.include_sources else "records.jsonl")
        if not file.exists():
            parser.error("run build first")
        for line in file.read_text(encoding="utf-8").splitlines():
            r = json.loads(line)
            if (args.type and r["record_type"] != args.type) or (args.verification and r["verification_status"] != args.verification) or (args.entity and r.get("entity_id") != args.entity):
                continue
            if args.query.casefold() in json.dumps(r, ensure_ascii=False).casefold():
                matches = [{"identifier": value, "role": role} for key, role in (("primary_identifiers", "primary"), ("identifier_candidates", "candidate-non-primary"), ("referenced_identifiers", "reference-non-primary")) for value in r.get(key, []) if args.query.casefold() in value.casefold()]
                if matches:
                    r["identifier_matches"] = matches
                print(json_text(r), end="")
        return 0
    records = scan(root)
    issues, summary = issue_summary(records)
    if args.command == "build":
        differences = build(root, records, args.check)
        print(json_text({"mode": "check" if args.check else "write", "different_files": differences, **summary}, True), end="")
        return int(bool(differences) and args.check)
    if args.command == "baseline":
        output = args.output if args.output.is_absolute() else root / args.output
        try:
            write_baseline(output, issues, args.reason)
        except ValueError as error:
            print(str(error), file=sys.stderr)
            print(json_text(summary, True), end="")
            return 2
        print(json_text({"baseline": str(output), **summary}, True), end="")
        return 0
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json_text({"summary": summary, "issues": [asdict(i) for i in issues]}, True), encoding="utf-8")
    if args.baseline:
        file = args.baseline if args.baseline.is_absolute() else root / args.baseline
        if not file.exists():
            print("baseline not found: " + str(file), file=sys.stderr)
            return 2
        added, resolved = baseline_delta(issues, json.loads(file.read_text(encoding="utf-8")))
        blocked = summary["fatal_issues"]
        summary.update({"new_issues": sum(added.values()), "resolved_issues": sum(resolved.values()), "baseline_issues_remaining": len(issues) - sum(added.values()), "result": "fatal quality blockers" if blocked else "new quality debt" if added else "no new debt; historical issues remain" if issues else "clean"})
        for issue in issues:
            if issue.key in added or issue.code in FATAL_CODES:
                print(json_text(asdict(issue)), end="", file=sys.stderr)
        print(json_text(summary, True), end="")
        return int(bool(added) or bool(blocked))
    print(json_text(summary, True), end="")
    return int(bool(issues))


if __name__ == "__main__":
    sys.exit(main())
